main: ${plugin.main}
name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
api-version: ${plugin.api-version}
author: ${plugin.author}
depend: [JsonMessageMaker]
commands:
  match:
    description: Called by a bot to join a match.
  sp:
    description: Allows you to spectate a bot match.